plugins {
    id 'java-library'
    id 'maven-publish'
}

group = providers.gradleProperty('group').getOrElse('br.gov.es.pmo')
version = providers.gradleProperty('version').getOrElse('1.0.1')

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    api 'com.github.sep-es-br:openpmo-plugin-publicIdentity-check-interface:v1.0.1'

    implementation 'org.springframework.boot:spring-boot-autoconfigure:2.2.12.RELEASE'
    implementation 'org.springframework.security:spring-security-oauth2-client:5.2.12.RELEASE'
    implementation 'org.apache.httpcomponents:httpclient:4.5.12'
    implementation 'org.json:json:20190722'
    implementation 'com.github.sep-es-br:pmo-core-identity-parser:1.0.6'

    testImplementation 'junit:junit:4.13.2'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'openpmo-plugin-publicIdentity-check-goves'
        }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
